name: test
description: SQL Snowflake demo project
version: 1.3.1
author: null
language: sql
buildSystem: ''
buildSystemDetails: null
pipelines: {}
datasets: {}
templates: {}
jobs:
  jobs/job1:
    name: job1
    description: ''
    fabricUID: 11413
    scheduler:
      Prophecy: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: 0 0 * * 1
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Multi: {}
      clusterId: null
    enabled: false
    createdAt: '2024-04-10 18:47:54'
    author: bobw@prophecy.io
    models: []
    sqlProjects: []
  jobs/job2:
    name: job2
    description: ''
    fabricUID: 9769
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: 0 0 0 ? * 1 *
    timeout: null
    alerting:
      emails: bobw@prophecy.io
      onStart: false
      onSuccess: false
      onFailure: true
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2024-04-17 18:43:35'
    author: bobw@prophecy.io
    models: []
    sqlProjects: []
  jobs/bobjob:
    name: bobjob
    description: ''
    fabricUID: 13760
    scheduler:
      Prophecy: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: None
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2025-01-21 18:47:11'
    author: bobw@prophecy.io
    models: []
    sqlProjects: []
gemContainer:
  languageVersion: ''
  gemLibsVersion: ''
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-03-28 13:57:47'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels:
  .prophecy/metadata/sqlmodels/dbt_util_sample:
    name: dbt_util_sample
    schema:
      entityType: ''
      providerType: Snowflake
      fields:
      - name: USER_ID
        dataType:
          type: String
      - name: EVENT
        dataType:
          type: String
      - name: VERSION
        dataType:
          type: String
      - name: VERSION_DATE
        dataType:
          type: Date
      - name: VERSION_DOY
        dataType:
          type: Number
    description: Deduplicates and transforms data from the `DEDUP_TEST` table. It
      creates a deduplicated list of events with corresponding user IDs, event types,
      versions, and dates. Additionally, it adds a new column `version_doy` representing
      the day of the year for the `VERSION_DATE`. The final result includes all columns
      from the `add_dbt_fx` table.
    author: bobw@prophecy.io
    files:
    - models/dbt_util_sample.sql
    - .prophecy/ide/models/dbt_util_sample.json
    - models/schema.yml
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-06-21 13:28:40'
  .prophecy/metadata/sqlmodels/test_csv:
    name: test_csv
    schema:
      entityType: ''
      providerType: Snowflake
      fields:
      - name: EMPLOYEE_ID
        dataType:
          type: Number
      - name: F_NAME
        dataType:
          type: String
      - name: L_NAME
        dataType:
          type: String
      - name: TITLE
        dataType:
          type: String
      - name: MANAGER_ID
        dataType:
          type: Number
    description: null
    author: bobw@prophecy.io
    files:
    - models/test_csv.sql
    - .prophecy/ide/models/test_csv.json
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-05-28 19:55:37'
  .prophecy/metadata/sqlmodels/demo_new_sql:
    name: demo_new_sql
    schema:
      entityType: ''
      providerType: Snowflake
      fields:
      - name: FULL_NAME
        dataType:
          type: String
      - name: COMPANY_NAME
        dataType:
          type: Variant
      - name: TOTAL_SALES
        dataType:
          type: Float
      - name: ORDER_COUNT
        dataType:
          type: Number
    description: Aggregates and summarizes sales data by customer, providing insights
      into total sales and order counts. It combines customer and order information,
      formats names, and extracts company domains from email addresses. The final
      output presents the top 50 customers based on total sales.
    author: bobw@prophecy.io
    files:
    - models/demo_new_sql.sql
    - .prophecy/ide/models/demo_new_sql.json
    - models/schema.yml
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2025-01-09 14:59:50'
  .prophecy/metadata/sqlmodels/sales_report:
    name: sales_report
    schema:
      entityType: ''
      providerType: Snowflake
      fields:
      - name: CUSTOMER_ID
        dataType:
          type: Number
      - name: FULL_NAME
        dataType:
          type: String
      - name: ORDER_COUNT
        dataType:
          type: Number
      - name: TOTAL_SALES
        dataType:
          type: Float
    description: Aggregates sales data by customer, summarizing total sales and order
      counts. It joins customer and order information, cleans up the data, and ranks
      the top customers based on sales, returning the top ten.
    author: bobw@prophecy.io
    files:
    - models/sales_report.sql
    - .prophecy/ide/models/sales_report.json
    - models/schema.yml
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-04-09 13:43:30'
  .prophecy/metadata/sqlmodels/customer_nations:
    name: customer_nations
    schema:
      entityType: ''
      providerType: Snowflake
      fields:
      - name: N_NAME
        dataType:
          type: String
      - name: C_NAME
        dataType:
          type: String
      - name: C_CUSTKEY
        dataType:
          type: Number
    description: null
    author: bobw@prophecy.io
    files:
    - models/customer_nations.sql
    - .prophecy/ide/models/customer_nations.json
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-04-01 15:23:32'
  .prophecy/metadata/sqlmodels/test12:
    name: test12
    schema:
      entityType: ''
      providerType: Snowflake
      fields:
      - name: FULL_NAME
        dataType:
          type: String
      - name: ORDER_COUNT
        dataType:
          type: Number
      - name: TOTAL_SALES
        dataType:
          type: Float
    description: null
    author: bobw@prophecy.io
    files:
    - models/test12.sql
    - .prophecy/ide/models/test12.json
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-07-12 20:10:39'
  .prophecy/metadata/sqlmodels/Join_SubGraph:
    name: Join_SubGraph
    schema:
      entityType: ''
      providerType: Snowflake
      fields:
      - name: EMPLOYEE_ID
        dataType:
          type: Number
      - name: F_NAME
        dataType:
          type: String
      - name: L_NAME
        dataType:
          type: String
      - name: TITLE
        dataType:
          type: String
      - name: MANAGER_ID
        dataType:
          type: Number
    description: null
    author: bobw@prophecy.io
    files:
    - models/Join_SubGraph.sql
    - .prophecy/ide/models/Join_SubGraph.json
    - models/schema.yml
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-09-06 15:22:21'
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds:
  .prophecy/metadata/sqlseeds/nations:
    name: nations
    schema:
      entityType: ''
      providerType: Snowflake
      fields:
      - name: n_nationkey
        dataType:
          type: Number
      - name: n_name
        dataType:
          type: String
      - name: n_regionkey
        dataType:
          type: Number
      - name: n_comment
        dataType:
          type: String
    description: null
    author: bobw@prophecy.io
    files:
    - seeds/nations.csv
    createdAt: '2024-04-01 15:24:59'
  .prophecy/metadata/sqlseeds/stooges:
    name: stooges
    schema:
      entityType: ''
      providerType: Snowflake
      fields:
      - name: employee_id
        dataType:
          type: Number
      - name: f_name
        dataType:
          type: String
      - name: l_name
        dataType:
          type: String
      - name: title
        dataType:
          type: String
      - name: manager_id
        dataType:
          type: Number
    description: null
    author: bobw@prophecy.io
    files:
    - seeds/stooges.csv
    createdAt: '2024-05-28 20:00:03'
sqlSources:
  .prophecy/metadata/sqlsources/BOBW_DEMO_OUTPUT:
    name: BOBW.DEMO_OUTPUT
    description: null
    author: bobw@prophecy.io
    files:
    - prophecy-sources/sources.yml
    createdAt: '2024-06-05 20:50:40'
    tables:
    - name: NATIONS
      schema:
        entityType: ''
        providerType: snowflake
        fields:
        - name: N_NATIONKEY
          dataType:
            type: Number
        - name: N_NAME
          dataType:
            type: String
        - name: N_REGIONKEY
          dataType:
            type: Number
        - name: N_COMMENT
          dataType:
            type: String
      description: null
      author: bobw@prophecy.io
      createdAt: '2024-06-05 20:50:40'
    - name: DEDUP_TEST
      schema:
        entityType: ''
        providerType: snowflake
        fields:
        - name: USER_ID
          dataType:
            type: String
        - name: EVENT
          dataType:
            type: String
        - name: VERSION
          dataType:
            type: String
        - name: DATE
          dataType:
            type: Date
      description: User event records for tracking interactions and versions over
        time.
      author: bobw@prophecy.io
      createdAt: '2024-06-21 13:33:00'
    - name: DEMO_BOB22
      schema:
        entityType: ''
        providerType: snowflake
        fields:
        - name: FULL_NAME
          dataType:
            type: String
        - name: TOTAL_SALES
          dataType:
            type: Float
        - name: ORDER_COUNT
          dataType:
            type: Number
      description: null
      author: bobw@prophecy.io
      createdAt: '2024-08-15 17:19:43'
    - name: STOOGES
      schema:
        entityType: ''
        providerType: snowflake
        fields:
        - name: EMPLOYEE_ID
          dataType:
            type: Number
        - name: F_NAME
          dataType:
            type: String
        - name: L_NAME
          dataType:
            type: String
        - name: TITLE
          dataType:
            type: String
        - name: MANAGER_ID
          dataType:
            type: Number
      description: Employee information including names, titles, and managerial relationships,
        supporting workforce management and organizational structure analysis.
      author: bobw@prophecy.io
      createdAt: '2024-08-15 19:33:09'
    - name: DEMO_IMPEL
      schema:
        entityType: ''
        providerType: snowflake
        fields:
        - name: FULL_NAME
          dataType:
            type: String
        - name: TOTAL_SALES
          dataType:
            type: Float
        - name: ORDER_COUNT
          dataType:
            type: Number
      description: null
      author: bobw@prophecy.io
      createdAt: '2024-08-15 19:45:01'
    - name: SALES_REPORT
      schema:
        entityType: ''
        providerType: snowflake
        fields:
        - name: CUSTOMER_ID
          dataType:
            type: Number
        - name: FULL_NAME
          dataType:
            type: String
        - name: ORDER_COUNT
          dataType:
            type: Number
        - name: TOTAL_SALES
          dataType:
            type: Float
      description: Customer sales performance data, summarizing order counts and total
        sales for each customer.
      author: bobw@prophecy.io
      createdAt: '2024-08-20 17:20:30'
    - name: TEST
      schema:
        entityType: ''
        providerType: snowflake
        fields:
        - name: EMPLOYEE_ID
          dataType:
            type: Number
        - name: F_NAME
          dataType:
            type: String
        - name: L_NAME
          dataType:
            type: String
        - name: TITLE
          dataType:
            type: String
        - name: MANAGER_ID
          dataType:
            type: Number
      description: null
      author: bobw@prophecy.io
      createdAt: '2024-08-29 17:32:10'
    - name: DEMO_BW
      schema:
        entityType: ''
        providerType: snowflake
        fields:
        - name: CUSTOMER_ID
          dataType:
            type: Number
        - name: FULL_NAME
          dataType:
            type: String
        - name: ORDER_COUNT
          dataType:
            type: Number
        - name: TOTAL_SALES
          dataType:
            type: Float
      description: Customer order and sales data, providing insights into order frequency
        and total sales per customer.
      author: bobw@prophecy.io
      createdAt: '2024-10-25 16:55:09'
    - name: TOP_SALES
      schema:
        entityType: ''
        providerType: snowflake
        fields:
        - name: CUSTOMER_ID
          dataType:
            type: Number
        - name: FIRST_NAME
          dataType:
            type: String
        - name: LAST_NAME
          dataType:
            type: String
        - name: REVENUE
          dataType:
            type: Float
        - name: ORDER_COUNT
          dataType:
            type: Number
      description: Top sales data highlighting revenue, customer details, and order
        counts, enabling insights into high-performing customers.
      author: bobw@prophecy.io
      createdAt: '2024-10-25 17:22:44'
    - name: DEMO_OPTUM
      schema:
        entityType: ''
        providerType: snowflake
        fields:
        - name: FULLNAME
          dataType:
            type: String
        - name: TOTAL_SALES
          dataType:
            type: Float
        - name: ORDER_COUNT
          dataType:
            type: Number
      description: Sales performance metrics including total sales and order counts,
        providing insights into overall business performance.
      author: bobw@prophecy.io
      createdAt: '2024-10-25 17:42:12'
    - name: WEBINAR_10
      schema:
        entityType: ''
        providerType: snowflake
        fields:
        - name: DEPARTMENT_NAME
          dataType:
            type: String
        - name: MANAGER_NAME
          dataType:
            type: String
        - name: TRAINING_ID
          dataType:
            type: String
        - name: TRAINING_DATE
          dataType:
            type: String
        - name: EMPLOYEE_NAME
          dataType:
            type: String
        - name: EMPLOYEE_ID
          dataType:
            type: String
        - name: EMPLOYEE_ADDRESS
          dataType:
            type: String
        - name: EMPLOYEE_START_DATE
          dataType:
            type: String
      description: null
      author: bobw@prophecy.io
      createdAt: '2024-10-30 13:17:35'
    - name: DEMO_TEST1
      schema:
        entityType: ''
        providerType: snowflake
        fields:
        - name: FULL_NAME
          dataType:
            type: String
        - name: TOTAL_SALES
          dataType:
            type: Float
        - name: ORDER_COUNT
          dataType:
            type: Number
      description: Sales performance metrics including total sales and order counts,
        aiding in business performance evaluation.
      author: bobw@prophecy.io
      createdAt: '2025-01-09 15:08:08'
    - name: DEMO_BNY1
      schema:
        entityType: ''
        providerType: snowflake
        fields:
        - name: FULL_NAME
          dataType:
            type: String
        - name: TOTAL_SALES
          dataType:
            type: Float
        - name: ORDER_COUNT
          dataType:
            type: Number
      description: Sales performance data capturing total sales, order counts, and
        customer names, enabling insights into sales trends and customer engagement.
      author: bobw@prophecy.io
      createdAt: '2025-01-09 17:31:48'
  .prophecy/metadata/sqlsources/BOBW_HELLOWORLD:
    name: BOBW.HELLOWORLD
    description: null
    author: bobw@prophecy.io
    files:
    - prophecy-sources/sources.yml
    createdAt: '2024-04-09 13:44:06'
    tables:
    - name: HW_ORDERS
      schema:
        entityType: ''
        providerType: snowflake
        fields:
        - name: ORDER_ID
          dataType:
            type: Number
        - name: CUSTOMER_ID
          dataType:
            type: Number
        - name: ORDER_STATUS
          dataType:
            type: String
        - name: ORDER_CATEGORY
          dataType:
            type: String
        - name: ORDER_DATE
          dataType:
            type: String
        - name: AMOUNT
          dataType:
            type: Float
      description: Tracks hardware orders placed by customers, including order details
        such as order status, category, date, and amount.
      author: bobw@prophecy.io
      createdAt: '2024-04-09 13:44:06'
    - name: HW_CUSTOMERS
      schema:
        entityType: ''
        providerType: snowflake
        fields:
        - name: CUSTOMER_ID
          dataType:
            type: Number
        - name: FIRST_NAME
          dataType:
            type: String
        - name: LAST_NAME
          dataType:
            type: String
        - name: PHONE
          dataType:
            type: String
        - name: EMAIL
          dataType:
            type: String
        - name: COUNTRY_CODE
          dataType:
            type: String
        - name: ACCOUNT_OPEN_DATE
          dataType:
            type: String
        - name: ACCOUNT_FLAGS
          dataType:
            type: String
      description: Customer data including their personal information, contact details,
        account details, and account flags. This dataset provides insights into customer
        profiles and account information.
      author: bobw@prophecy.io
      createdAt: '2024-04-09 13:44:22'
  .prophecy/metadata/sqlsources/SNOWFLAKE_SAMPLE_DATA_TPCH_SF10:
    name: SNOWFLAKE_SAMPLE_DATA.TPCH_SF10
    description: null
    author: bobw@prophecy.io
    files:
    - prophecy-sources/sources.yml
    createdAt: '2024-04-17 19:03:51'
    tables:
    - name: CUSTOMER
      schema:
        entityType: ''
        providerType: snowflake
        fields:
        - name: C_CUSTKEY
          dataType:
            type: Number
        - name: C_NAME
          dataType:
            type: String
        - name: C_ADDRESS
          dataType:
            type: String
        - name: C_NATIONKEY
          dataType:
            type: Number
        - name: C_PHONE
          dataType:
            type: String
        - name: C_ACCTBAL
          dataType:
            type: Number
        - name: C_MKTSEGMENT
          dataType:
            type: String
        - name: C_COMMENT
          dataType:
            type: String
      description: null
      author: bobw@prophecy.io
      createdAt: '2024-04-17 19:03:51'
sqlUnreferencedSources: {}
sqlPipeline:
  name: sqlPipeline
  description: null
  author: bobw@prophecy.io
  createdAt: '2024-03-28 13:57:47'
dependencies: '[]'
projectDependencies: {}
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
