name: test
description: SQL Snowflake demo project
version: '1'
author: null
language: sql
buildSystem: ''
buildSystemDetails: null
pipelines: {}
datasets: {}
templates: {}
jobs:
  jobs/job1:
    name: job1
    description: ''
    fabricUID: 11413
    scheduler:
      Prophecy: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: 0 0 * * 1
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Multi: {}
      clusterId: null
    enabled: false
    createdAt: '2024-04-10 18:47:54'
    author: bobw@prophecy.io
  jobs/job2:
    name: job2
    description: ''
    fabricUID: 9769
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: 0 0 0 ? * 1 *
    timeout: null
    alerting:
      emails: bobw@prophecy.io
      onStart: false
      onSuccess: false
      onFailure: true
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2024-04-17 18:43:35'
    author: bobw@prophecy.io
gemContainer:
  languageVersion: ''
  gemLibsVersion: ''
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-03-28 13:57:47'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels:
  .prophecy/metadata/sqlmodels/dbt_util_sample:
    name: dbt_util_sample
    schema:
      providerType: Snowflake
      fields:
      - name: USER_ID
        dataType:
          type: String
      - name: EVENT
        dataType:
          type: String
      - name: VERSION
        dataType:
          type: String
      - name: VERSION_DATE
        dataType:
          type: Date
      - name: VERSION_DOY
        dataType:
          type: Number
    description: Deduplicates and transforms data from the `DEDUP_TEST` table. It
      creates a deduplicated list of events with corresponding user IDs, event types,
      versions, and dates. Additionally, it adds a new column `version_doy` representing
      the day of the year for the `VERSION_DATE`. The final result includes all columns
      from the `add_dbt_fx` table.
    author: bobw@prophecy.io
    files:
    - models/dbt_util_sample.sql
    - .prophecy/ide/models/dbt_util_sample.json
    - models/schema.yml
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-06-21 13:28:40'
  .prophecy/metadata/sqlmodels/test_csv:
    name: test_csv
    schema:
      providerType: Snowflake
      fields:
      - name: EMPLOYEE_ID
        dataType:
          type: Number
      - name: F_NAME
        dataType:
          type: String
      - name: L_NAME
        dataType:
          type: String
      - name: TITLE
        dataType:
          type: String
      - name: MANAGER_ID
        dataType:
          type: Number
    description: null
    author: bobw@prophecy.io
    files:
    - models/test_csv.sql
    - .prophecy/ide/models/test_csv.json
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-05-28 19:55:37'
  .prophecy/metadata/sqlmodels/sales_report:
    name: sales_report
    schema:
      providerType: Snowflake
      fields:
      - name: CUSTOMER_ID
        dataType:
          type: Number
      - name: FULL_NAME
        dataType:
          type: String
      - name: ORDER_COUNT
        dataType:
          type: Number
      - name: TOTAL_SALES
        dataType:
          type: Float
    description: null
    author: bobw@prophecy.io
    files:
    - models/sales_report.sql
    - .prophecy/ide/models/sales_report.json
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-04-09 13:43:30'
  .prophecy/metadata/sqlmodels/customer_nations:
    name: customer_nations
    schema:
      providerType: Snowflake
      fields:
      - name: N_NAME
        dataType:
          type: String
      - name: C_NAME
        dataType:
          type: String
      - name: C_CUSTKEY
        dataType:
          type: Number
    description: null
    author: bobw@prophecy.io
    files:
    - models/customer_nations.sql
    - .prophecy/ide/models/customer_nations.json
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-04-01 15:23:32'
  .prophecy/metadata/sqlmodels/cpSQL:
    name: cpSQL
    schema:
      providerType: Snowflake
      fields:
      - name: C_NAME
        dataType:
          type: String
      - name: TOTAL_SALES
        dataType:
          type: Float
    description: This pipeline graph provides insights into the top 15 customers with
      the highest total sales. By joining the 'HW_ORDERS' table from the 'BOBW.HELLOWORLD'
      source with the 'CUSTOMER' table from the 'SNOWFLAKE_SAMPLE_DATA.TPCH_SF10'
      source, it combines order and customer information. The resulting dataset includes
      details such as order ID, customer ID, order status, order category, order date,
      amount, customer name, customer address, customer phone number, customer account
      balance, customer market segment, and customer comments. By summarizing the
      total sales for each customer and ordering them in descending order, businesses
      can identify their top-performing customers and tailor their marketing and sales
      strategies accordingly.
    author: bobw@prophecy.io
    files:
    - models/cpSQL.sql
    - .prophecy/ide/models/cpSQL.json
    - models/schema.yml
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-05-02 16:58:34'
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds:
  .prophecy/metadata/sqlseeds/nations:
    name: nations
    schema:
      providerType: Snowflake
      fields:
      - name: n_nationkey
        dataType:
          type: Number
      - name: n_name
        dataType:
          type: String
      - name: n_regionkey
        dataType:
          type: Number
      - name: n_comment
        dataType:
          type: String
    description: null
    author: bobw@prophecy.io
    files:
    - seeds/nations.csv
    createdAt: '2024-04-01 15:24:59'
  .prophecy/metadata/sqlseeds/stooges:
    name: stooges
    schema:
      providerType: Snowflake
      fields:
      - name: employee_id
        dataType:
          type: Number
      - name: f_name
        dataType:
          type: String
      - name: l_name
        dataType:
          type: String
      - name: title
        dataType:
          type: String
      - name: manager_id
        dataType:
          type: Number
    description: null
    author: bobw@prophecy.io
    files:
    - seeds/stooges.csv
    createdAt: '2024-05-28 20:00:03'
sqlSources:
  .prophecy/metadata/sqlsources/BOBW_DEMO_OUTPUT:
    name: BOBW.DEMO_OUTPUT
    description: null
    author: bobw@prophecy.io
    files:
    - prophecy-sources/sources.yml
    createdAt: '2024-06-05 20:50:40'
    tables:
    - name: NATIONS
      schema:
        providerType: snowflake
        fields:
        - name: N_NATIONKEY
          dataType:
            type: Number
        - name: N_NAME
          dataType:
            type: String
        - name: N_REGIONKEY
          dataType:
            type: Number
        - name: N_COMMENT
          dataType:
            type: String
      description: null
      author: bobw@prophecy.io
      createdAt: '2024-06-05 20:50:40'
    - name: DEDUP_TEST
      schema:
        providerType: snowflake
        fields:
        - name: USER_ID
          dataType:
            type: String
        - name: EVENT
          dataType:
            type: String
        - name: VERSION
          dataType:
            type: String
        - name: DATE
          dataType:
            type: Date
      description: null
      author: bobw@prophecy.io
      createdAt: '2024-06-21 13:33:00'
  .prophecy/metadata/sqlsources/BOBW_HELLOWORLD:
    name: BOBW.HELLOWORLD
    description: null
    author: bobw@prophecy.io
    files:
    - prophecy-sources/sources.yml
    createdAt: '2024-04-09 13:44:06'
    tables:
    - name: HW_ORDERS
      schema:
        providerType: snowflake
        fields:
        - name: ORDER_ID
          dataType:
            type: Number
        - name: CUSTOMER_ID
          dataType:
            type: Number
        - name: ORDER_STATUS
          dataType:
            type: String
        - name: ORDER_CATEGORY
          dataType:
            type: String
        - name: ORDER_DATE
          dataType:
            type: String
        - name: AMOUNT
          dataType:
            type: Float
      description: null
      author: bobw@prophecy.io
      createdAt: '2024-04-09 13:44:06'
    - name: HW_CUSTOMERS
      schema:
        providerType: snowflake
        fields:
        - name: CUSTOMER_ID
          dataType:
            type: Number
        - name: FIRST_NAME
          dataType:
            type: String
        - name: LAST_NAME
          dataType:
            type: String
        - name: PHONE
          dataType:
            type: String
        - name: EMAIL
          dataType:
            type: String
        - name: COUNTRY_CODE
          dataType:
            type: String
        - name: ACCOUNT_OPEN_DATE
          dataType:
            type: String
        - name: ACCOUNT_FLAGS
          dataType:
            type: String
      description: null
      author: bobw@prophecy.io
      createdAt: '2024-04-09 13:44:22'
  .prophecy/metadata/sqlsources/SNOWFLAKE_SAMPLE_DATA_TPCH_SF10:
    name: SNOWFLAKE_SAMPLE_DATA.TPCH_SF10
    description: null
    author: bobw@prophecy.io
    files:
    - prophecy-sources/sources.yml
    createdAt: '2024-04-17 19:03:51'
    tables:
    - name: CUSTOMER
      schema:
        providerType: snowflake
        fields:
        - name: C_CUSTKEY
          dataType:
            type: Number
        - name: C_NAME
          dataType:
            type: String
        - name: C_ADDRESS
          dataType:
            type: String
        - name: C_NATIONKEY
          dataType:
            type: Number
        - name: C_PHONE
          dataType:
            type: String
        - name: C_ACCTBAL
          dataType:
            type: Number
        - name: C_MKTSEGMENT
          dataType:
            type: String
        - name: C_COMMENT
          dataType:
            type: String
      description: null
      author: bobw@prophecy.io
      createdAt: '2024-04-17 19:03:51'
sqlUnreferencedSources: {}
sqlPipeline:
  name: sqlPipeline
  description: null
  author: bobw@prophecy.io
  createdAt: '2024-03-28 13:57:47'
dependencies: '[]'
projectDependencies: {}
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
