---
version: 2
sources:
- name: "BOBW.HELLOWORLD"
  database: "BOBW"
  schema: "HELLOWORLD"
  config:
    enabled: true
  tables:
  - name: "HW_ORDERS"
    columns:
    - name: "ORDER_ID"
      dataType:
        type: "Number"
    - name: "CUSTOMER_ID"
      dataType:
        type: "Number"
    - name: "ORDER_STATUS"
      dataType:
        type: "String"
    - name: "ORDER_CATEGORY"
      dataType:
        type: "String"
    - name: "ORDER_DATE"
      dataType:
        type: "String"
    - name: "AMOUNT"
      dataType:
        type: "Float"
  - name: "HW_CUSTOMERS"
    columns:
    - name: "CUSTOMER_ID"
      dataType:
        type: "Number"
    - name: "FIRST_NAME"
      dataType:
        type: "String"
    - name: "LAST_NAME"
      dataType:
        type: "String"
    - name: "PHONE"
      dataType:
        type: "String"
    - name: "EMAIL"
      dataType:
        type: "String"
    - name: "COUNTRY_CODE"
      dataType:
        type: "String"
    - name: "ACCOUNT_OPEN_DATE"
      dataType:
        type: "String"
    - name: "ACCOUNT_FLAGS"
      dataType:
        type: "String"
- name: "SNOWFLAKE_SAMPLE_DATA.TPCH_SF10"
  database: "SNOWFLAKE_SAMPLE_DATA"
  schema: "TPCH_SF10"
  config:
    enabled: true
  tables:
  - name: "CUSTOMER"
    columns:
    - name: "C_CUSTKEY"
      dataType:
        type: "Number"
    - name: "C_NAME"
      dataType:
        type: "String"
    - name: "C_ADDRESS"
      dataType:
        type: "String"
    - name: "C_NATIONKEY"
      dataType:
        type: "Number"
    - name: "C_PHONE"
      dataType:
        type: "String"
    - name: "C_ACCTBAL"
      dataType:
        type: "Number"
    - name: "C_MKTSEGMENT"
      dataType:
        type: "String"
    - name: "C_COMMENT"
      dataType:
        type: "String"
- name: "BOBW.DEMO_OUTPUT"
  database: "BOBW"
  schema: "DEMO_OUTPUT"
  config:
    enabled: true
  tables:
  - name: "NATIONS"
    columns:
    - name: "N_NATIONKEY"
      dataType:
        type: "Number"
    - name: "N_NAME"
      dataType:
        type: "String"
    - name: "N_REGIONKEY"
      dataType:
        type: "Number"
    - name: "N_COMMENT"
      dataType:
        type: "String"
  - name: "DEDUP_TEST"
    columns:
    - name: "USER_ID"
      dataType:
        type: "String"
    - name: "EVENT"
      dataType:
        type: "String"
    - name: "VERSION"
      dataType:
        type: "String"
    - name: "DATE"
      dataType:
        type: "Date"
