{{
  config({    
    "materialized": "table"
  })
}}

WITH HW_CUSTOMERS AS (

  SELECT * 
  
  FROM {{ source('BOBW.HELLOWORLD', 'HW_CUSTOMERS') }}

),

HW_ORDERS AS (

  SELECT * 
  
  FROM {{ source('BOBW.HELLOWORLD', 'HW_ORDERS') }}

),

by_CUSTOMER_ID AS (

  SELECT 
    HW_ORDERS.CUSTOMER_ID AS CUSTOMER_ID,
    HW_CUSTOMERS.FIRST_NAME AS FIRST_NAME,
    HW_CUSTOMERS.LAST_NAME AS LAST_NAME,
    HW_ORDERS.ORDER_ID AS ORDER_ID,
    HW_ORDERS.AMOUNT AS AMOUNT,
    HW_CUSTOMERS.PHONE AS PHONE,
    HW_CUSTOMERS.EMAIL AS EMAIL,
    HW_CUSTOMERS.COUNTRY_CODE AS COUNTRY_CODE,
    HW_CUSTOMERS.ACCOUNT_OPEN_DATE AS ACCOUNT_OPEN_DATE,
    HW_CUSTOMERS.ACCOUNT_FLAGS AS ACCOUNT_FLAGS,
    HW_ORDERS.ORDER_STATUS AS ORDER_STATUS,
    HW_ORDERS.ORDER_DATE AS ORDER_DATE,
    HW_ORDERS.ORDER_CATEGORY AS ORDER_CATEGORY
  
  FROM HW_ORDERS
  INNER JOIN HW_CUSTOMERS
     ON HW_ORDERS.CUSTOMER_ID = HW_CUSTOMERS.CUSTOMER_ID

),

clean_up AS (

  SELECT 
    CUSTOMER_ID AS CUSTOMER_ID,
    CONCAT(FIRST_NAME, ' ', LAST_NAME) AS FULL_NAME,
    ORDER_ID AS ORDER_ID,
    AMOUNT AS AMOUNT
  
  FROM by_CUSTOMER_ID

),

Aggregate_sales AS (

  SELECT 
    any_value(CUSTOMER_ID) AS CUSTOMER_ID,
    any_value(FULL_NAME) AS FULL_NAME,
    COUNT(ORDER_ID) AS order_count,
    SUM(AMOUNT) AS total_sales
  
  FROM clean_up
  
  GROUP BY 
    CUSTOMER_ID, FULL_NAME

),

OrderBySales AS (

  SELECT * 
  
  FROM Aggregate_sales
  
  ORDER BY TOTAL_SALES DESC

),

Limit_Top AS (

  SELECT * 
  
  FROM OrderBySales AS in0
  
  LIMIT 10

)

SELECT *

FROM Limit_Top
