---
version: 2
models:
- name: "dbt_util_sample"
  description: "Deduplicates and transforms data from the `DEDUP_TEST` table. It creates\
    \ a deduplicated list of events with corresponding user IDs, event types, versions,\
    \ and dates. Additionally, it adds a new column `version_doy` representing the\
    \ day of the year for the `VERSION_DATE`. The final result includes all columns\
    \ from the `add_dbt_fx` table."
  columns: []
- name: "Join_SubGraph"
  columns:
  - name: "CUSTOMER_ID"
    dataType:
      type: "Number"
  - name: "FIRST_NAME"
    dataType:
      type: "String"
  - name: "LAST_NAME"
    dataType:
      type: "String"
  - name: "PHONE"
    dataType:
      type: "String"
  - name: "EMAIL"
    dataType:
      type: "String"
  - name: "COUNTRY_CODE"
    dataType:
      type: "String"
  - name: "ACCOUNT_OPEN_DATE"
    dataType:
      type: "String"
  - name: "ACCOUNT_FLAGS"
    dataType:
      type: "String"
  - name: "ORDER_ID"
    dataType:
      type: "Number"
  - name: "ORDER_STATUS"
    dataType:
      type: "String"
  - name: "ORDER_CATEGORY"
    dataType:
      type: "String"
  - name: "ORDER_DATE"
    dataType:
      type: "String"
  - name: "SALES_AMOUNT"
    dataType:
      type: "Float"
- name: "sales_report"
  description: "Aggregates sales data by customer, summarizing total sales and order\
    \ counts. It joins customer and order information, cleans up the data, and ranks\
    \ the top customers based on sales, returning the top ten."
  columns:
  - name: "CUSTOMER_ID"
    dataType:
      type: "Number"
  - name: "FULL_NAME"
    dataType:
      type: "String"
  - name: "ORDER_COUNT"
    dataType:
      type: "Number"
  - name: "TOTAL_SALES"
    dataType:
      type: "Float"
- name: "demo_new_sql"
  description: "Aggregates and summarizes sales data by customer, providing insights\
    \ into total sales and order counts. It combines customer and order information,\
    \ formats names, and extracts company domains from email addresses. The final\
    \ output presents the top 50 customers based on total sales."
  columns:
  - name: "FULL_NAME"
    dataType:
      type: "String"
  - name: "TOTAL_SALES"
    dataType:
      type: "Float"
  - name: "ORDER_COUNT"
    dataType:
      type: "Number"
  tests: []
sources: []
